name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-with-maven:
    name: Build with maven
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14

      - uses: actions/checkout@v2

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Build the Docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: fozat/stock-price-service:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
